spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6380

global:
  redis:
    host: localhost
    port: 6379

instance:
  node-id: 17

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19500