server:
  port: 19300

spring:
  application:
    name: feed-service

  datasource:
    url: jdbc:postgresql://localhost:5432/feeddb
    username: feeduser
    password: feedpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/