spring:
  application:
    name: chat-service
  profiles:
    active: local

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


instance:
  node-id: 13

jwt:
  key: ${SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000