spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_DATABASE_NAME}
    username: ${RDS_DATABASE_USERNAME}
    password: ${RDS_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${AWS_REDIS_ENDPOINT}
      port: ${AWS_REDIS_PORT}

server:
  port: 19200

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

  instance:
    prefer-ip-address: true
    ip-address: 3.39.22.236
    instance-id: chat-service:3.39.22.236:19200

presence:
  service:
    url: ${PRESENCE_SERVICE_ENDPOINT}